name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sign_in_button: ^3.0.0
  firebase_core: any
  firebase_auth: any
  google_sign_in: any
  cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
