name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  path: any
  path_provider: any
  provider: ^6.0.5
  sign_in_button: ^3.0.0
  firebase_core: any
  firebase_auth: any
  google_sign_in: any
  cloud_firestore: any
  logger: ^2.0.0
  fl_chart: ^0.70.2
  image_picker: any
  google_mlkit_text_recognition: any
  flutter_vision: ^1.1.4
  image: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/best_float32.tflite
    - assets/labels.txt
